# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='desination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='inventory.Warehouse'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='inventory.Warehouse'),
        ),
    ]
