# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20161016_1242'),
        ('inventory', '0005_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Account'),
        ),
    ]
