# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
