# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170212_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.FloatField(default=0, null=True),
        ),
    ]
