# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_GLP', models.CharField(max_length=7)),
                ('account_Angaza', models.CharField(max_length=8)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='date hired')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('location', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='date hired')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('district', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='payment date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upfront', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('weekly', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Manager'),
        ),
        migrations.AddField(
            model_name='account',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Agent'),
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Client'),
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Plan'),
        ),
    ]
