# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sales', '0001_initial'), ('sales', '0002_auto_20160930_0555'), ('sales', '0003_auto_20161001_0904'), ('sales', '0004_auto_20161001_0918'), ('sales', '0005_auto_20161001_0936'), ('sales', '0006_auto_20161001_0937'), ('sales', '0007_agent_login'), ('sales', '0008_payment_id_angaza'), ('sales', '0009_auto_20161001_1128'), ('sales', '0010_agent_warehouse'), ('sales', '0011_auto_20161001_1422'), ('sales', '0012_auto_20161016_1242'), ('sales', '0013_payment_credit_after'), ('sales', '0014_auto_20161105_1745'), ('sales', '0015_payment_paid_left'), ('sales', '0016_payment_is_last'), ('sales', '0017_auto_20161105_1946'), ('sales', '0018_auto_20161105_2344'), ('sales', '0019_payment_perfect_date'), ('sales', '0020_payment_is_upfront'), ('sales', '0021_account_unlock_date'), ('sales', '0022_agent_category'), ('sales', '0023_auto_20170212_1221'), ('sales', '0024_account_plan_iscash'), ('sales', '0025_complan'), ('sales', '0026_agent_com'), ('sales', '0027_auto_20170427_2228'), ('sales', '0028_auto_20170427_2229')]

    initial = True

    dependencies = [
        ('inventory', '0005_product_label'),
        ('inventory', '0004_auto_20160926_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_Angaza', models.CharField(max_length=8)),
                ('account_GLP', models.CharField(max_length=7)),
                ('plan_name', models.CharField(max_length=40)),
                ('plan_up', models.PositiveIntegerField(default=0)),
                ('plan_tot', models.PositiveIntegerField(default=0)),
                ('plan_week', models.PositiveIntegerField(default=0)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
                ('status', models.CharField(choices=[('a', 'Activated'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], default='a', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='date hired')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=1, null=True)),
                ('location', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='date hired')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('district', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='payment date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Agent')),
                ('id_Angaza', models.CharField(max_length=8, null=True)),
                ('days_left_before', models.FloatField(default=0, null=True)),
                ('paid_after', models.PositiveIntegerField(default=0, null=True)),
                ('paid_left', models.PositiveIntegerField(default=0, null=True)),
                ('is_last', models.NullBooleanField()),
                ('next_disable', models.DateTimeField(null=True, verbose_name='next disable date')),
                ('perfect_date', models.DateTimeField(null=True, verbose_name='perfect disable date')),
                ('is_upfront', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Manager'),
        ),
        migrations.AddField(
            model_name='account',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Agent'),
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Client'),
        ),
        migrations.AddField(
            model_name='account',
            name='plan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('a', 'Activated'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('a', 'Activated'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('e', 'Activated'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('e', 'Active'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], max_length=1),
        ),
        migrations.AddField(
            model_name='agent',
            name='login',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('e', 'Enabled'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off'), ('r', 'Reposessed')], max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='unlock_date',
            field=models.DateTimeField(null=True, verbose_name='unlock date'),
        ),
        migrations.AddField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('R', 'Rural'), ('F', 'Freetown'), ('H', 'HQ'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plan_iscash',
            field=models.NullBooleanField(),
        ),
        migrations.CreateModel(
            name='ComPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stipend', models.PositiveIntegerField(default=0)),
                ('top_up', models.PositiveIntegerField(default=0)),
                ('transport', models.PositiveIntegerField(default=0)),
                ('trigger1', models.PositiveIntegerField(default=0)),
                ('bonus1', models.PositiveIntegerField(default=0)),
                ('trigger2', models.PositiveIntegerField(default=0)),
                ('bonus2', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='com',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.ComPlan'),
        ),
        migrations.AddField(
            model_name='agent',
            name='uid',
            field=models.CharField(default='US000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
