# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
