# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170427_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='aid',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
