# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20160930_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('a', 'Activated'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], max_length=10),
        ),
    ]
