# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20160921_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('a', 'Activated'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off')], default='a', max_length=10),
        ),
    ]
