# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_agent_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='gender',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_left',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
