# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20161001_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='login',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
