# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20170429_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('A', 'Agent'), ('F', 'Freelancer'), ('M', 'Manager'), ('D', 'Distributor'), ('C', 'Call Center'), ('T', 'Technical Team'), ('R', 'Field Rep'), ('H', 'HQ'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
