# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_agent_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_angaza',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
