# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-29 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20170429_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='label',
            new_name='label_angaza',
        ),
    ]
