# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-29 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20170429_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('F', 'Manual (Field)'), ('H', 'Manual (HQ)'), ('M', 'Mobile Money')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Agent'),
        ),
    ]
