# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_payment_id_angaza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='id_angaza',
            new_name='id_Angaza',
        ),
    ]
