# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20170429_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id_Angaza',
            field=models.CharField(default='PA000000', max_length=8),
        ),
    ]
