# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_label'),
        ('sales', '0009_auto_20161001_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse'),
        ),
    ]
