# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-29 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20170429_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='label_angaza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='uid',
            field=models.CharField(default='US000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0000111122223333', max_length=16),
        ),
    ]
