# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_agent_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse'),
        ),
    ]
