# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20161001_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('e', 'Enabled'), ('d', 'Deactivated'), ('u', 'Unlocked'), ('w', 'Written Off'), ('r', 'Reposessed')], max_length=1),
        ),
    ]
