# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20170429_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_upfront',
            new_name='is_downpayment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='next_disable',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='perfect_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateTimeField(null=True, verbose_name='next expiry date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date_0',
            field=models.DateTimeField(null=True, verbose_name='next expiry date if 100% active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
