# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20161016_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_after',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
