# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_payment_paid_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_last',
            field=models.NullBooleanField(),
        ),
    ]
