# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_payment_is_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='credit_after',
        ),
        migrations.AddField(
            model_name='payment',
            name='next_disable',
            field=models.DateTimeField(null=True, verbose_name='next disable date'),
        ),
    ]
