# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20161105_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='credit_before',
            new_name='days_left_before',
        ),
    ]
