# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_payment_perfect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_upfront',
            field=models.NullBooleanField(),
        ),
    ]
