# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_account_unlock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('R', 'Rural'), ('F', 'Freetown'), ('H', 'HQ'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
