# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_agent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
