# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20170212_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan_iscash',
            field=models.NullBooleanField(),
        ),
    ]
