# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_account_plan_iscash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stipend', models.PositiveIntegerField(default=0)),
                ('top_up', models.PositiveIntegerField(default=0)),
                ('transport', models.PositiveIntegerField(default=0)),
                ('trigger1', models.PositiveIntegerField(default=0)),
                ('bonus1', models.PositiveIntegerField(default=0)),
                ('trigger2', models.PositiveIntegerField(default=0)),
                ('bonus2', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
