# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_auto_20170427_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='ID',
            new_name='uid',
        ),
    ]
