# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='update date')),
                ('is_full', models.BooleanField()),
                ('hours', models.FloatField(default=0)),
                ('new_clients', models.IntegerField(default=0)),
                ('new_accs', models.IntegerField(default=0)),
                ('new_pays', models.IntegerField(default=0)),
            ],
        ),
    ]
